framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            App\Message\TaskUpdatedNotification: sync

when@dev:
    framework:
        messenger:
            transports:
                async: 'sync://'

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
